Recipe app
EidHachem/RecipeOnRails pull request #18
Opened 2022-08-31 11:45 UTC by EidHachem

## In this PR @mavericks-db  and I implemented the following:

    - A login page.
    - A registration page.
    - A food list (with all CRUD implementation, except for 'update').
    - A recipes list (with all CRUD implementation, except for 'update').
    - A general shopping list view (all missing food for all your recipes and total price).
    - A list of all public recipes from other users with their names and total prices.

2022-08-31 12:36 UTC, dasileker requested changes
### **Hi @EidHachem,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**
- Linters are green ✅.
- Pr is very nice 👌.
- The readme file is nice ✅.
- Commit are consistent 👌.

## Required Changes ♻️
_Check the comments under the review._

- **Hello and nice job on your capstone but there is some minor issue encountered while reviewing your projects**one while adding ingredients it's returning undefined and the second is the test suits are failing*`*. so please fix those and re-submit again.**

![Capture d’écran 2022-08-31 132826](https://user-images.githubusercontent.com/61562626/187679739-2d7901dd-6bd5-40b1-adaa-5b7fccdaeb26.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-31 12:36 UTC, dasileker commented on app/controllers/recipe_foods_controller.rb
> +  end
- [ ] Please make sure that the `@recipe_food` can add the food to the recipe, right now is generating an error of undefined.

![Capture d’écran 2022-08-31 132350](https://user-images.githubusercontent.com/61562626/187678912-b39f2a8c-a56f-4c6c-be7d-67874f67ad7f.png)

2022-09-01 06:07 UTC, mavericks-db commented on app/controllers/recipe_foods_controller.rb
> +  end
Done in [4efdd10](https://github.com/EidHachem/RecipeOnRails/pull/18/commits/4efdd10cd950b97b2629b47b443ce1a5c71aa522)

2022-09-01 07:31 UTC, Davidosky007 approved these changes
Hi @EidHachem @mavericks-db 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors ;
* All tests passed ✔️ 
* Good looking readme file 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-01 07:34 UTC, mavericks-db commented
Thank you 👍

2022-09-01 07:35 UTC, merged